import dropbox
import os
from modzy import ApiClient
from modzy._util import file_to_bytes

#Initialize Modzy and Dropbox clients
client = ApiClient(base_url=os.getenv("MODZY_BASE_URL"), api_key=os.getenv("MODZY_API_KEY"))
dbx = dropbox.Dropbox(os.getenv("DROPBOX_ACCESS_TOKEN"))

def main():
    #Runs an inference on each image in this folder and then save the image to Dropbox
    image_folder = "images-test"
    for filename in os.listdir(image_folder):
        f = os.path.join(image_folder,filename)
        
        #Sends the image to Modzy for inference and get back a Job ID number
        job_ID = modzy_inference(f,filename)
        print("Inference Job Identifier: " + job_ID)
        
        #Upload the source image to Dropbox and name it after the Job ID generated by Modzy so they can later be matched
        upload_image(f,job_ID)

def modzy_inference(image_path,image_ID):
    #Creates the input sources object and base64 encodes the image
    sources = {}
    sources[image_ID] = {
        "image": file_to_bytes(image_path),
    }

    #Submits the image to a model that performs Image-based Geolocation
    model_id = "aevbu1h3yw"
    model_version = "1.0.1"
    job = client.jobs.submit_file(model_id, model_version, sources, explain=True)
    return job.get("jobIdentifier")

def upload_image(image_path,image_ID):    
    #Uploads the image to Dropbox
    dbx.files_upload(file_to_bytes(image_path),'/' + str(image_ID) + '.jpg')

if __name__ == '__main__':
    main()